version: '3.7'

services:
  finance_back:
    build: ./
    command: make run
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
  finance-db:
    image: postgres:14.6-alpine
    volumes:
      - finance_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
volumes:
  finance_postgres_data: