version: '3.7'

services:
  finance-db:
    image: postgres:14.6-alpine
    container_name: finance-db
    networks:
        - djangonetwork
    volumes:
      - finance_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env
  finance_back:
    build: ./
    depends_on:
        - finance-db
    links:
        - finance-db:finance-db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
volumes:
  finance_postgres_data:
networks:
  djangonetwork:
    driver: bridge