version: '3.7'

services:
  financedb:
    image: postgres:14.6-alpine
    container_name: financedb
    volumes:
      - finance_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  finance:
    build: ./
    container_name: finance
    # command: >
    #   sh -c "python manage.py migrate && uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload"
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - financedb

volumes:
  finance_postgres_data:
